# ===========================
# Etapa 1 - Build do Angular usando Bun
# ===========================
# Substituímos o node:22-alpine pelo bun oficial em versão alpine
FROM oven/bun:alpine AS build

WORKDIR /app

# Copia os arquivos de dependências (o bun usa o bun.lockb ou package.json)
COPY ./sos_app/package*.json ./

# 'bun install --frozen-lockfile' é o equivalente ao 'npm ci'
RUN bun install --frozen-lockfile

COPY ./sos_app .

# Executa o script de build usando o bun
RUN bun run build:dev -- --progress=false

# ===========================
# Etapa 2 - Nginx (Permanece igual)
# ===========================
FROM nginx:alpine

COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# O Angular continuará gerando os arquivos estáticos na mesma pasta
COPY --from=build /app/www/browser /usr/share/nginx/html